package gui.frame;

import model.UserList;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author USER
 */
public class signUp extends javax.swing.JFrame {

	/**
	 * Creates new form Table
	 */
	public signUp() {
		initComponents();
		getContentPane().setBackground(new Color(204, 204, 204));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Password2 = new javax.swing.JTextField();
		Username = new javax.swing.JTextField();
		Password = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("RESTAURANT POS (made by Kit&Bank)");
		setBackground(new java.awt.Color(204, 204, 204));
		setResizable(false);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		Password2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
		Password2.setForeground(new java.awt.Color(51, 51, 0));
		getContentPane().add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 395, 536, -1));

		Username.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
		Username.setForeground(new java.awt.Color(51, 51, 0));
		Username.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				UsernameActionPerformed(evt);
			}
		});
		getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 536, -1));

		Password.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
		Password.setForeground(new java.awt.Color(51, 51, 0));
		Password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PasswordActionPerformed(evt);
			}
		});
		getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 316, 536, -1));

		jButton1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
		jButton1.setText("cancel");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 502, -1, 60));

		jButton2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
		jButton2.setText("confirm");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 502, 145, 60));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
		jLabel2.setText("SIGN UP");
		getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 160, 50));

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
		jLabel3.setText("password :");
		getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, 50));

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
		jLabel4.setText("confirm password :");
		getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 50));

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
		jLabel5.setText("username :");
		getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 170, 50));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Background/newwww.jpg"))); // NOI18N
		getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 740));

		setBounds(400, 200, 1208, 787);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		try {
			new Login().setVisible(true);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(signUp.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(signUp.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(signUp.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(signUp.class.getName()).log(Level.SEVERE, null, ex);
		}
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	static JFrame error = new JFrame("Problem");

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		if (Password.getText().equals("") || Password2.getText().equals("") || Username.getText().equals("")) {
			error.setSize(401, 401);
			JOptionPane.showMessageDialog(error, "The textfield must not be empty!");
		} else {
			if (Password.getText().equals(Password2.getText())) {

				if (!UserList.getthatUser(Username.getText()) && !UserList.getthatPass(Password.getText())) {
					try {
						UserList.addUser(Username.getText(), Password.getText());
						new Login().setVisible(true);
						this.dispose();
					} catch (IOException ex) {
						Logger.getLogger(signUp.class.getName()).log(Level.SEVERE, null, ex);
					} catch (ClassNotFoundException e) {
						e.printStackTrace();
					} catch (InstantiationException e) {
						e.printStackTrace();
					} catch (IllegalAccessException e) {
						e.printStackTrace();
					} catch (UnsupportedLookAndFeelException e) {
						e.printStackTrace();
					}
				} else {
					error.setSize(401, 401);
					JOptionPane.showMessageDialog(error, "This username or password is already in used!");
				}

			} else {
				error.setSize(401, 401);
				JOptionPane.showMessageDialog(error, "The password does not match!");
			}
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UsernameActionPerformed
	}// GEN-LAST:event_UsernameActionPerformed

	private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PasswordActionPerformed
	}// GEN-LAST:event_PasswordActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField Password;
	private javax.swing.JTextField Password2;
	private javax.swing.JTextField Username;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables
}
